export const USER_COLLECTION_LIMIT = 20;
export const USER_COLLECTION_TAG_LIMIT = 50;
export const USER_COLLECTION_ITEM_LIMIT = 1000;
export const COLLECTION_ITEM_PER_COLLECTION_LIMIT = 300;
export const USER_ARCHIVE_MUTATION_BODY_LIMIT_BYTES = 16 * 1024;

export const COLLECTION_NAME_MAX_LENGTH = 80;
export const COLLECTION_DESCRIPTION_MAX_LENGTH = 500;
export const COLLECTION_ITEM_NOTE_MAX_LENGTH = 500;
export const TAG_NAME_MAX_LENGTH = 40;
export const TAGS_PER_ITEM_LIMIT = 10;
