#!/usr/bin/env sh
MESSAGE_FILE="$1" node <<'NODE'
const fs = require('node:fs');

const messageFile = process.env.MESSAGE_FILE;

if (!messageFile) {
	console.error('缺少 commit message 文件路径。');
	process.exit(1);
}

const messageLine = fs.readFileSync(messageFile, 'utf8').split(/\r?\n/)[0].replace(/\r$/, '');

const allowedTypes = [
	'feat',
	'fix',
	'refactor',
	'style',
	'docs',
	'chore',
	'test',
	'build',
	'ci',
	'perf',
	'revert',
];

const normalCommitPattern = new RegExp('^(' + allowedTypes.join('|') + '): \\S.*');
const mergeCommitPattern = /^Merge .*/;

if (normalCommitPattern.test(messageLine) || mergeCommitPattern.test(messageLine)) {
	process.exit(0);
}

console.error(
	'提交 message 必须以 ' +
		allowedTypes.join(' / ') +
		' 中的一个开头，后接冒号、空格和说明，例如：feat: add login page；或者是 Merge commit，例如：Merge branch \'dev\' into main'
);

process.exit(1);
NODE